apiVersion: apps/v1
kind: Deployment
metadata:
    name: server-deployment
    labels:
        app: add
spec:
    selector:
        matchLabels:
            app: add
    replicas: 2
    template:
        metadata:
            labels:
                app: add
        spec:
            containers:
                - name: add
                  image: idoko/adder-server:v1.0
                  ports:
                    - name: server-service
                      containerPort: 5000

---
apiVersion: v1
kind: Service
metadata:
    name: server-service
spec:
    selector: 
        app: add
    ports:
        - port: 5000
          targetPort: server-service